#!/usr/bin/make -f

image=prometheus
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

grafanatag=7.5.10@sha256:7d28577eae379351336172ca626a5158331f6407f9aaab0a4570c8a3c54ef286

runargs=--publish-all

grafanarunargs=--publish-all
