#!/usr/bin/make -f

image=prometheus
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

grafanatag=7.5.10@sha256:7d28577eae379351336172ca626a5158331f6407f9aaab0a4570c8a3c54ef286

runargs=--publish-all

grafanarunargs=--publish-all
